version: '3.7'

services:
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_cron
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    image: "postgrest/postgrest:v12.0.1"
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: ${DB_URI}
      PGRST_DB_SCHEMAS: "api"
      PGRST_DB_ANON_ROLE: "web_anon"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: null
