version: '3.7'

services:
  db:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_cron
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: null
